package com.healthsync.ai.recommendation.service.impl;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.healthsync.ai.recommendation.entity.Activity;
import com.healthsync.ai.recommendation.entity.Recommendation;
import com.healthsync.ai.recommendation.service.ActivityAIService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

@RequiredArgsConstructor
@Service
@Slf4j
public class ActivityAIServiceImpl implements ActivityAIService {

    private final GeminiAIServiceImpl geminiAIServiceImpl;

    @Override
    public Recommendation generateRecommendation(Activity activity) {

        String prompt = createPromptForActivity(activity);

        String aiResponse = geminiAIServiceImpl.getRecommendations(prompt);

        log.info("RESPONSE FROM AI: {}", aiResponse);

        return processAIResponse(activity, aiResponse);
    }

    @Override
    public Recommendation processAIResponse(
            Activity activity,
            String aiResponse
    ) {

        try {
            ObjectMapper mapper = new ObjectMapper();

            JsonNode rootNode = mapper.readTree(aiResponse);

            /*
             * Gemini Interactions API response structure:
             *
             * {
             *   "object": "interaction",
             *   "model": "gemini-3.6-flash",
             *   "steps": [
             *      {
             *          "type": "thought"
             *      },
             *      {
             *          "type": "model_output",
             *          "content": [
             *              {
             *                  "text": "```json ... ```"
             *              }
             *          ]
             *      }
             *   ]
             * }
             */

            JsonNode stepsNode = rootNode.path("steps");

            if (!stepsNode.isArray() || stepsNode.isEmpty()) {
                throw new IllegalStateException(
                        "Invalid Gemini response: 'steps' not found or empty"
                );
            }

            JsonNode textNode = findModelOutputText(stepsNode);

            if (textNode == null || textNode.isMissingNode()) {
                throw new IllegalStateException(
                        "Invalid Gemini response: model output text not found"
                );
            }

            String jsonContent = cleanJsonResponse(textNode.asText());

            if (jsonContent.isBlank()) {
                throw new IllegalStateException(
                        "Gemini returned empty response"
                );
            }

            log.info("CLEANED AI RESPONSE: {}", jsonContent);

            /*
             * Parse the JSON generated by Gemini.
             */
            JsonNode analysisJson = mapper.readTree(jsonContent);

            JsonNode analysisNode = analysisJson.path("analysis");

            /*
             * Build complete analysis text.
             */
            StringBuilder fullAnalysis = new StringBuilder();

            addAnalysisSection(
                    fullAnalysis,
                    analysisNode,
                    "overall",
                    "Overall:"
            );

            addAnalysisSection(
                    fullAnalysis,
                    analysisNode,
                    "pace",
                    "Pace:"
            );

            addAnalysisSection(
                    fullAnalysis,
                    analysisNode,
                    "heartRate",
                    "Heart Rate:"
            );

            addAnalysisSection(
                    fullAnalysis,
                    analysisNode,
                    "caloriesBurned",
                    "Calories:"
            );

            /*
             * Extract remaining recommendation sections.
             */
            List<String> improvements =
                    extractImprovements(
                            analysisJson.path("improvements")
                    );

            List<String> suggestions =
                    extractSuggestions(
                            analysisJson.path("suggestions")
                    );

            List<String> safety =
                    extractSafetyGuidelines(
                            analysisJson.path("safety")
                    );

            /*
             * Build Recommendation entity.
             */
            return Recommendation.builder()
                    .activityId(activity.getId())
                    .userId(activity.getUserId())
                    .type(activity.getType().toString())
                    .recommendation(fullAnalysis.toString().trim())
                    .improvements(improvements)
                    .suggestions(suggestions)
                    .safety(safety)
                    .createdAt(LocalDateTime.now())
                    .build();

        } catch (Exception e) {

            log.error(
                    "Failed to process Gemini AI response for activityId={}",
                    activity.getId(),
                    e
            );

            return createDefaultRecommendation(activity);
        }
    }

    /**
     * Finds the text generated by Gemini from the Interactions API response.
     *
     * Response structure:
     *
     * steps[]
     *   └── model_output
     *        └── content[]
     *             └── text
     */
    private JsonNode findModelOutputText(JsonNode stepsNode) {

        for (JsonNode step : stepsNode) {

            String stepType = step.path("type").asText();

            if (!"model_output".equals(stepType)) {
                continue;
            }

            JsonNode contentNode = step.path("content");

            if (!contentNode.isArray() || contentNode.isEmpty()) {
                continue;
            }

            for (JsonNode content : contentNode) {

                JsonNode textNode = content.path("text");

                if (!textNode.isMissingNode()
                        && !textNode.isNull()
                        && !textNode.asText().isBlank()) {

                    return textNode;
                }
            }
        }

        return null;
    }

    /**
     * Removes Markdown code fences from Gemini's JSON response.
     *
     * Example:
     *
     * ```json
     * {
     *   "analysis": {}
     * }
     * ```
     *
     * becomes:
     *
     * {
     *   "analysis": {}
     * }
     */
    private String cleanJsonResponse(String response) {

        if (response == null) {
            return "";
        }

        String cleaned = response.trim();

        if (cleaned.startsWith("```json")) {
            cleaned = cleaned.substring("```json".length()).trim();
        } else if (cleaned.startsWith("```")) {
            cleaned = cleaned.substring("```".length()).trim();
        }

        if (cleaned.endsWith("```")) {
            cleaned = cleaned.substring(
                    0,
                    cleaned.length() - 3
            ).trim();
        }

        return cleaned;
    }

    @Override
    public Recommendation createDefaultRecommendation(
            Activity activity
    ) {

        return Recommendation.builder()
                .activityId(activity.getId())
                .userId(activity.getUserId())
                .type(activity.getType().toString())
                .recommendation(
                        "Unable to generate detailed analysis"
                )
                .improvements(
                        Collections.singletonList(
                                "Continue with your current routine"
                        )
                )
                .suggestions(
                        Collections.singletonList(
                                "Consider consulting a fitness consultant"
                        )
                )
                .safety(
                        Arrays.asList(
                                "Always warm up before exercise",
                                "Stay hydrated",
                                "Listen to your body"
                        )
                )
                .createdAt(LocalDateTime.now())
                .build();
    }

    @Override
    public List<String> extractSafetyGuidelines(
            JsonNode safetyNode
    ) {

        List<String> safety = new ArrayList<>();

        if (safetyNode.isArray()) {

            safetyNode.forEach(item -> {

                if (!item.isNull() && !item.asText().isBlank()) {
                    safety.add(item.asText());
                }
            });
        }

        return safety.isEmpty()
                ? Collections.singletonList(
                "Follow general safety guidelines"
        )
                : safety;
    }

    @Override
    public List<String> extractSuggestions(
            JsonNode suggestionsNode
    ) {

        List<String> suggestions = new ArrayList<>();

        if (suggestionsNode.isArray()) {

            suggestionsNode.forEach(suggestion -> {

                String workout =
                        suggestion.path("workout").asText("");

                String description =
                        suggestion.path("description").asText("");

                if (!workout.isBlank() || !description.isBlank()) {

                    if (workout.isBlank()) {
                        suggestions.add(description);
                    } else if (description.isBlank()) {
                        suggestions.add(workout);
                    } else {
                        suggestions.add(
                                String.format(
                                        "%s: %s",
                                        workout,
                                        description
                                )
                        );
                    }
                }
            });
        }

        return suggestions.isEmpty()
                ? Collections.singletonList(
                "No specific suggestions provided"
        )
                : suggestions;
    }

    @Override
    public List<String> extractImprovements(
            JsonNode improvementsNode
    ) {

        List<String> improvements = new ArrayList<>();

        if (improvementsNode.isArray()) {

            improvementsNode.forEach(improvement -> {

                String area =
                        improvement.path("area").asText("");

                String recommendation =
                        improvement.path("recommendation").asText("");

                if (!area.isBlank() || !recommendation.isBlank()) {

                    if (area.isBlank()) {
                        improvements.add(recommendation);
                    } else if (recommendation.isBlank()) {
                        improvements.add(area);
                    } else {
                        improvements.add(
                                String.format(
                                        "%s: %s",
                                        area,
                                        recommendation
                                )
                        );
                    }
                }
            });
        }

        return improvements.isEmpty()
                ? Collections.singletonList(
                "No specific improvements provided"
        )
                : improvements;
    }

    @Override
    public void addAnalysisSection(
            StringBuilder fullAnalysis,
            JsonNode analysisNode,
            String key,
            String prefix
    ) {

        JsonNode valueNode = analysisNode.path(key);

        if (!valueNode.isMissingNode()
                && !valueNode.isNull()
                && !valueNode.asText().isBlank()) {

            fullAnalysis
                    .append(prefix)
                    .append(" ")
                    .append(valueNode.asText())
                    .append("\n\n");
        }
    }

    @Override
    public String createPromptForActivity(
            Activity activity
    ) {

        return String.format(
                """
                Analyze this fitness activity and provide detailed recommendations in the following EXACT JSON format:

                {
                  "analysis": {
                    "overall": "Overall analysis here",
                    "pace": "Pace analysis here",
                    "heartRate": "Heart rate analysis here",
                    "caloriesBurned": "Calories analysis here"
                  },
                  "improvements": [
                    {
                      "area": "Area name",
                      "recommendation": "Detailed recommendation"
                    }
                  ],
                  "suggestions": [
                    {
                      "workout": "Workout name",
                      "description": "Detailed workout description"
                    }
                  ],
                  "safety": [
                    "Safety point 1",
                    "Safety point 2"
                  ]
                }

                Analyze this activity:

                Activity Type: %s
                Duration: %d minutes
                Calories Burned: %d
                Additional Metrics: %s

                Provide detailed analysis focusing on:
                - Performance
                - Improvements
                - Next workout suggestions
                - Safety guidelines

                Return ONLY valid JSON.
                Do not add Markdown code fences.
                Do not add explanations outside the JSON.
                """,
                activity.getType(),
                activity.getDuration(),
                activity.getCaloriesBurned(),
                activity.getAdditionalMetrics()
        );
    }
}